controllers:
    resource: ../src/Controller/
    type: attribute

user_index:
  path: /user
  controller: App\Controller\UserController::index
  methods: GET

user_register:
  path: /register
  controller: App\Controller\UserController::register
  methods: POST

user_login:
  path: /login
  controller: App\Controller\UserController::login
  methods: POST

user_update:
  path: /update
  controller: App\Controller\UserController::update
  methods: PUT

user_contact:
  path: /contact
  controller: App\Controller\UserController::contact
  methods: POST

app_logout:
  path: /logout
  controller: App\Controller\UserController::logout
  methods: [POST, DELETE]

get_all_users:
  path: /getallusers
  controller: App\Controller\UserController::getAllUsers
  methods: GET